--!strict
local Object = require("@self/Object");
local Instance = require("@self/Instance");
local BasePart = require("@self/BasePart");
local DataModel = require("@self/DataModel");
local GuiObject = require("@self/GuiObject");
local GuiButton = require("@self/GuiButton");

return {
    Object = Object,
    Instance = Instance,
    BasePart = BasePart,
    DataModel = DataModel,
    GuiObject = GuiObject,
    GuiButton = GuiButton,
}
