--!strict
return {
    base64 = require("@self/base64"),
    blake2 = require("@self/blake2"),
    datetime = require("@self/datetime"),
    lz4 = require("@self/lz4"),
    md5 = require("@self/md5"),
    mem = require("@self/mem"),
    sink = require("@self/sink"),
    stream = require("@self/stream"),
    task = require("@self/task"),
    zlib = require("@self/zlib"),
    zstd = require("@self/zstd"),
}